#!/usr/bin/env python3
"""把人工撰写的 Echo 样本写成 train/val（非模板池抽样）。

每条 (user_text, think, utter, 控制字段) 一一对应，禁止 random.choice 拼装。
"""

from __future__ import annotations

import argparse
import json
import random
import sys
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from structured_llm.contract import validate_turn

SCHEMA = ROOT / "schemas" / "echo_turn.schema.json"
OUT_DIR = ROOT / "examples" / "echo" / "sample_data"


def _out(
    think: str,
    utter: str,
    emotion: str,
    volume: int,
    pace: str,
    should_speak: bool,
    intent: str,
    ui_mode: str,
    end_turn: bool,
) -> str:
    payload = {
        "utter": utter,
        "emotion": emotion,
        "volume": volume,
        "pace": pace,
        "should_speak": should_speak,
        "intent": intent,
        "ui_mode": ui_mode,
        "end_turn": end_turn,
    }
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":"))
    return f"<think>\n{think}\n</think>\n\n[json]\n{body}\n[/json]"


def _row(
    sid: str,
    user_text: str,
    user_emotion: str,
    think: str,
    utter: str,
    emotion: str,
    volume: int,
    pace: str,
    intent: str,
    *,
    scenario: str,
    energy: int = 55,
    bond: int = 4,
    turn: int = 3,
    can_speak: bool = True,
    interruptible: bool = True,
    should_speak: bool | None = None,
    ui_mode: str | None = None,
    end_turn: bool = False,
    prior_utters: list[str] | None = None,
    multi_turn: bool = False,
    round_i: int | None = None,
) -> dict[str, Any]:
    if should_speak is None:
        should_speak = can_speak
    if ui_mode is None:
        ui_mode = "speak" if can_speak else "text_only"
    if not can_speak:
        should_speak = False
        ui_mode = "text_only"
        volume = 0
    meta: dict[str, Any] = {
        "scenario": scenario,
        "contract": "v3",
        "source": "handcrafted",
    }
    if multi_turn:
        meta["multi_turn"] = True
        if round_i is not None:
            meta["round"] = round_i
    return {
        "id": sid,
        "input": {
            "user_text": user_text,
            "user_emotion": user_emotion,
            "session": {"energy": energy, "bond": bond, "turn": turn},
            "device": {"can_speak": can_speak, "interruptible": interruptible},
        },
        "output": _out(
            think, utter, emotion, volume, pace, should_speak, intent, ui_mode, end_turn
        ),
        "prior_utters": list(prior_utters or []),
        "meta": meta,
    }


def build_single_turns() -> list[dict[str, Any]]:
    """单轮：每条用户话绑定唯一口播，带具体实体/约束。"""
    s: list[dict[str, Any]] = []

    # —— tired / comfort ——
    s += [
        _row("hc_tired_01", "连开了三场站会，脑子里还在回放那个延期表格。", "tired",
             "用户会议疲劳且惦记延期表；短句低音量 comfort。",
             "先别管那张表了。喝口水，闭眼三十秒。", "gentle", 28, "slow", "comfort",
             scenario="tired", energy=18, turn=2),
        _row("hc_tired_02", "孩子半夜醒了两次，我现在说话都飘。", "tired",
             "育儿失眠；安抚且不追问细节。",
             "你已经撑过半夜了。先靠一下，话可以慢慢说。", "gentle", 26, "slow", "comfort",
             scenario="tired", energy=20, bond=6, turn=5),
        _row("hc_tired_03", "代码改到凌晨两点，测试还红着三条。", "tired",
             "加班且测试失败；短 comfort，避免再加压。",
             "三条红可以明早再看。现在先存档，去躺平。", "gentle", 30, "slow", "comfort",
             scenario="tired", energy=22, turn=8),
        _row("hc_tired_04", "高铁误点四十分钟，站台风好大，我腿都僵了。", "tired",
             "旅途疲惫；低音量陪伴。",
             "风大就找挡风的地方站着。到了再跟我说一声。", "gentle", 32, "slow", "comfort",
             scenario="tired", energy=35, turn=1),
        _row("hc_tired_05", "今天被催了七次进度，耳膜都麻了。", "tired",
             "被催促耗尽；comfort，不复盘工作。",
             "七次够多了。这一刻不许再催自己。", "gentle", 27, "slow", "comfort",
             scenario="tired", energy=25, bond=5),
        _row("hc_tired_06", "眼睛干得睁不开，还想把周报写完。", "tired",
             "生理疲劳 vs 周报；劝停。",
             "周报写不完也没关系。先闭眼歇五分钟。", "gentle", 29, "slow", "comfort",
             scenario="tired", energy=24),
        _row("hc_tired_07", "健身房器械区人挤人，我练完只想躺地上。", "tired",
             "运动后力竭；轻声。",
             "那你就躺着喘匀。水先抿一口。", "gentle", 31, "slow", "comfort",
             scenario="tired", energy=40, turn=4),
        _row("hc_tired_08", "论文参考文献格式改到眼花，还差十篇。", "tired",
             "学术琐碎疲劳；comfort。",
             "十篇可以拆成明天的。今晚先停在这里。", "gentle", 28, "slow", "comfort",
             scenario="tired", energy=30, bond=3),
        _row("hc_tired_09", "客户把需求又改回第一版，我整个人空了。", "tired",
             "返工打击；安抚不站队骂客户。",
             "空很正常。先离开屏幕两分钟，我陪着。", "gentle", 30, "slow", "comfort",
             scenario="tired", energy=28),
        _row("hc_tired_10", "感冒第三天，嗓子像砂纸，还得值班。", "tired",
             "生病值班；低音量 comfort。",
             "砂纸嗓就少说话。值班能坐着就别站着。", "gentle", 24, "slow", "comfort",
             scenario="tired", energy=16, bond=5),
        _row("hc_tired_11", "搬家纸箱堆到门口，我连拖鞋都找不到。", "tired",
             "搬家混乱疲惫。",
             "拖鞋以后再找。先坐纸箱上喘口气。", "gentle", 33, "slow", "comfort",
             scenario="tired", energy=38, turn=6),
        _row("hc_tired_12", "刷题刷到第 47 道，正确率掉到四成，不想动了。", "tired",
             "备考挫败疲劳；收束压力。",
             "四成也说明你还在打。今天到 47 就收工。", "gentle", 29, "slow", "comfort",
             scenario="tired", energy=33),
    ]

    # —— happy / celebrate ——
    s += [
        _row("hc_happy_01", "产品上线第一小时就有 200 个真实用户点进来了！", "happy",
             "上线有真实流量；cheerful celebrate，点出 200。",
             "200 个真人进来，这波值得记一笔。最惊喜的是哪边？", "cheerful", 72, "normal", "celebrate",
             scenario="happy", energy=88, turn=2),
        _row("hc_happy_02", "牙医说我智齿不用拔，阴影拍片一切正常。", "happy",
             "医疗好消息；轻松祝贺。",
             "不用拔太好了。今晚可以好好吃饭庆祝一下。", "cheerful", 68, "normal", "celebrate",
             scenario="happy", energy=70),
        _row("hc_happy_03", "导师终于回邮件了，论文大纲他批了通过。", "happy",
             "学术进展；celebrate 点导师与大纲。",
             "大纲过关！下一步你最想先写哪一章？", "cheerful", 70, "normal", "celebrate",
             scenario="happy", energy=75, bond=4),
        _row("hc_happy_04", "相亲对象居然也养柯基，聊了两小时停不下来。", "happy",
             "社交契合；轻松 celebrate。",
             "同款柯基缘分太强了。下次还约咖啡吗？", "cheerful", 66, "normal", "celebrate",
             scenario="happy", energy=80, bond=3),
        _row("hc_happy_05", "房租续约谈下来了，房东同意冻价一年。", "happy",
             "经济压力缓解；celebrate。",
             "冻价一年稳了。今晚可以少惦记账单一点。", "cheerful", 65, "normal", "celebrate",
             scenario="happy", energy=72),
        _row("hc_happy_06", "马拉松跑完了，成绩比预期快了六分钟！", "happy",
             "运动突破；点出六分钟。",
             "快六分钟很猛。腿还抖吗，要不要先拉伸？", "cheerful", 74, "normal", "celebrate",
             scenario="happy", energy=85, turn=1),
        _row("hc_happy_07", "弟弟考上心仪的高中了，全家群刷屏。", "happy",
             "家人喜事；celebrate。",
             "刷屏有道理。你打算怎么给他庆功？", "cheerful", 71, "normal", "celebrate",
             scenario="happy", energy=78, bond=7),
        _row("hc_happy_08", "开源项目第一次被人 star 破千，我截图存了。", "happy",
             "开源里程碑；celebrate。",
             "破千值得截图。哪次提交你觉得最有含金量？", "cheerful", 69, "normal", "celebrate",
             scenario="happy", energy=82),
        _row("hc_happy_09", "体检报告下来，血脂终于回到绿区了。", "happy",
             "健康改善；温和 celebrate。",
             "绿区回来了。这段时间哪条习惯最管用？", "cheerful", 64, "normal", "celebrate",
             scenario="happy", energy=68),
        _row("hc_happy_10", "客户当场签字，合同金额比报价还高一档。", "happy",
             "商务胜利；celebrate 但不诱导炫富细节。",
             "高一档签字，漂亮。想先跟谁分享这句喜讯？", "cheerful", 73, "normal", "celebrate",
             scenario="happy", energy=90, bond=5),
        _row("hc_happy_11", "阳台番茄结了第一颗红的，我拍了二十张。", "happy",
             "生活小确幸；轻快。",
             "第一颗红番茄值得二十张。打算今天就尝尝吗？", "cheerful", 62, "normal", "celebrate",
             scenario="happy", energy=65, turn=9),
        _row("hc_happy_12", "英语口语课老师说我发音进步肉眼可见。", "happy",
             "学习反馈；celebrate。",
             "肉眼可见的进步最实在。哪句话你练得最顺？", "cheerful", 67, "normal", "celebrate",
             scenario="happy", energy=74),
    ]

    # —— anxious / clarify ——
    s += [
        _row("hc_anx_01", "周五要给董事会讲 Q3 下滑原因，PPT 还差两页关键灯片。", "anxious",
             "董事会演讲焦虑；clarify 收窄到最怕的环节。",
             "董事会压力大。你更卡的是数据页，还是问答？", "concerned", 48, "slow", "clarify",
             scenario="anxious", energy=42, turn=3),
        _row("hc_anx_02", "签证材料里缺一张在职证明，大使馆预约就在下周三。", "anxious",
             "签证材料缺口；clarify 下一步动作。",
             "下周三前还能补。在职证明卡在公司哪一环？", "concerned", 46, "slow", "clarify",
             scenario="anxious", energy=40),
        _row("hc_anx_03", "孩子发烧到 38.6，退烧药吃了，我还是想再量一次。", "anxious",
             "育儿健康焦虑；clarify 且不替代医疗建议。",
             "38.6 值得盯着。你是想确认量温间隔，还是要不要就医？", "concerned", 44, "slow", "clarify",
             scenario="anxious", energy=35, bond=7),
        _row("hc_anx_04", "合并请求被打回三次，评审说命名不清晰，我开始怀疑自己。", "anxious",
             "代码评审打击；clarify 具体卡点。",
             "三次打回很挫。命名这块，你最想先改哪个文件？", "concerned", 47, "slow", "clarify",
             scenario="anxious", energy=45),
        _row("hc_anx_05", "相亲前对方突然已读不回两天，我不知道还要不要出门。", "anxious",
             "社交不确定；clarify 决策。",
             "已读不回两天确实难受。你更倾向再等一天，还是直接改期？", "concerned", 45, "slow", "clarify",
             scenario="anxious", energy=38, bond=3),
        _row("hc_anx_06", "房东说下月可能转给中介，我怕涨租或者被清退。", "anxious",
             "住房不确定；clarify 信息缺口。",
             "转中介最怕的是涨租还是合同期限？我们先抓住一件。", "concerned", 49, "slow", "clarify",
             scenario="anxious", energy=41),
        _row("hc_anx_07", "体检出小结节要复查，报告写随诊，我脑子里全是最坏情况。", "anxious",
             "健康报告焦虑；clarify，避免恐吓。",
             "随诊不等于宣判。你最想先弄清的是复查时间，还是含义？", "concerned", 43, "slow", "clarify",
             scenario="anxious", energy=36, bond=6),
        _row("hc_anx_08", "团队里有人背后说我抢功，我不知道要不要找领导谈。", "anxious",
             "职场人际；clarify 目标。",
             "背后议论很伤。你更想先求证事实，还是直接对齐领导预期？", "concerned", 48, "slow", "clarify",
             scenario="anxious", energy=44),
        _row("hc_anx_09", "航班显示可能取消，改签口人排到拐角，我行李还在托运。", "anxious",
             "出行突发；clarify 优先动作。",
             "托运行李在，改签是第一优先吗？还是先问取消确认？", "concerned", 50, "normal", "clarify",
             scenario="anxious", energy=48, turn=1),
        _row("hc_anx_10", "存款只够撑三个月房租，下家工作还在面试第二轮。", "anxious",
             "财务与求职叠加；clarify 最沉的一块。",
             "三个月窗口很紧。眼下最沉的是面试准备，还是开销清单？", "concerned", 46, "slow", "clarify",
             scenario="anxious", energy=39, bond=4),
        _row("hc_anx_11", "开题报告被说文献综述太薄，重交期限只有五天。", "anxious",
             "学术 deadline；clarify。",
             "五天够紧。你是缺篇目数量，还是缺论证结构？", "concerned", 47, "slow", "clarify",
             scenario="anxious", energy=43),
        _row("hc_anx_12", "邻居装修从早上八点锤到晚上，我远程会一直被打断。", "anxious",
             "环境干扰影响工作；clarify 诉求。",
             "锤到晚上很难忍。你更想先换场地开会，还是先沟通静音时段？", "concerned", 49, "normal", "clarify",
             scenario="anxious", energy=50),
    ]

    # —— neutral / chat ——
    s += [
        _row("hc_chat_01", "提醒我四点半给盆栽浇水，用喷壶别直接浇根。", "neutral",
             "具体提醒；chat，复述关键约束。",
             "记下了：四点半，喷壶，别直接浇根。", "calm", 52, "normal", "chat",
             scenario="neutral", energy=55, turn=4),
        _row("hc_chat_02", "今天北京空气一般，适合户外跑吗？", "neutral",
             "天气运动咨询；简短 chat。",
             "空气一般的话，配速放慢或改室内走也行。", "calm", 50, "normal", "chat",
             scenario="neutral", energy=60),
        _row("hc_chat_03", "你在吗？我想随便吐槽两句地铁末班车。", "neutral",
             "闲聊邀请；chat。",
             "在。末班车哪段最想吐槽，挤还是延误？", "calm", 54, "normal", "chat",
             scenario="neutral", energy=58, bond=5),
        _row("hc_chat_04", "帮我在购物清单加上无糖酸奶和猫砂，猫砂买膨润土。", "neutral",
             "清单追加；复述品类。",
             "加好了：无糖酸奶，膨润土猫砂。还要别的吗？", "calm", 53, "normal", "chat",
             scenario="neutral", energy=57),
        _row("hc_chat_05", "现在这个点睡觉会不会太早？我通常十一点才困。", "neutral",
             "作息闲聊；chat。",
             "对你来说偏早也正常。想小睡还是先干点轻活？", "calm", 51, "normal", "chat",
             scenario="neutral", energy=52, turn=7),
        _row("hc_chat_06", "推荐一个十五分钟能做完的拉伸，针对久坐肩颈。", "neutral",
             "健身请求；chat，给短方案入口。",
             "先做肩绕环和门口胸开。要我按分钟拆开说吗？", "calm", 55, "normal", "chat",
             scenario="neutral", energy=56),
        _row("hc_chat_07", "明天有雨，我那件藏青色风衣洗了没干，备选是什么？", "neutral",
             "穿衣决策；chat。",
             "风衣没干就抓防水外套或带伞的薄外套。家里还有哪件？", "calm", 52, "normal", "chat",
             scenario="neutral", energy=54),
        _row("hc_chat_08", "把番茄钟设成二十五加五，开始第一轮写周报。", "neutral",
             "番茄钟确认；chat。",
             "二十五加五，第一轮写周报，开始。中途要停就喊我。", "calm", 56, "normal", "chat",
             scenario="neutral", energy=62, turn=2),
        _row("hc_chat_09", "附近新开的面馆排队到门口，值不值得等？", "neutral",
             "生活选择；chat。",
             "看你有多饿。能接受二十分钟队就试，否则改熟店也行。", "calm", 53, "normal", "chat",
             scenario="neutral", energy=59),
        _row("hc_chat_10", "我想听点不费脑的，聊聊你觉得云像什么。", "neutral",
             "轻松闲聊；chat。",
             "有时候像揉皱的棉被。你今晚窗外的云偏厚还是偏薄？", "calm", 50, "normal", "chat",
             scenario="neutral", energy=61, bond=6),
        _row("hc_chat_11", "闹钟设在六点四十，标签写晨跑，别用刺耳铃声。", "neutral",
             "闹钟设置；复述约束。",
             "六点四十晨跑，柔和铃声。设好了。", "calm", 54, "normal", "chat",
             scenario="neutral", energy=58),
        _row("hc_chat_12", "咖啡因今天已经两杯美式了，晚间改喝什么？", "neutral",
             "饮品建议；chat。",
             "两杯美式后晚间可以换无糖气泡水或热牛奶。", "calm", 51, "normal", "chat",
             scenario="neutral", energy=55),
    ]

    # —— playful / joke ——
    s += [
        _row("hc_play_01", "客户把按钮颜色改了第九版，我需要一点无厘头。", "sad",
             "职场琐碎；轻度 joke，点第九版。",
             "第九版可以叫终极传说色。要不要给它起个外号？", "playful", 60, "normal", "joke",
             scenario="playful", energy=48, turn=5),
        _row("hc_play_02", "减肥第十四天，晚上对冰箱门谈心了三分钟。", "sad",
             "节食崩溃边缘；joke 不嘲讽。",
             "冰箱门是很好的听众。今晚谈心协议：只开一次。", "playful", 58, "normal", "joke",
             scenario="playful", energy=50, bond=4),
        _row("hc_play_03", "我的盆栽叶子卷了，像不像它也在嫌弃我加班？", "sad",
             "拟人玩笑；joke。",
             "它大概在举牌：浇水或放假二选一。你选哪个？", "playful", 62, "normal", "joke",
             scenario="playful", energy=52),
        _row("hc_play_04", "面试官问五年规划，我脑子里只浮现想睡觉。", "sad",
             "面试事后；轻 joke。",
             "五年规划第一年：睡饱。要不要我帮你编个正经版备用？", "playful", 61, "normal", "joke",
             scenario="playful", energy=45),
        _row("hc_play_05", "快递把鞋码送成童码，我现在单脚踩着纸盒走路。", "sad",
             "物流乌龙；joke。",
             "纸盒鞋也算限定款。退换的同时要不要先找旧鞋应急？", "playful", 63, "normal", "joke",
             scenario="playful", energy=55, turn=3),
        _row("hc_play_06", "开会有人把共享屏幕停在表情包文件夹，全场静音三秒。", "happy",
             "社死名场面；joke。",
             "那三秒能进年度名场面。表情包英雄是你吗？", "playful", 64, "normal", "joke",
             scenario="playful", energy=70),
        _row("hc_play_07", "我养的多肉叶子掉光了，只剩光杆，像不像我的周末计划。", "sad",
             "自嘲；joke 接住比喻。",
             "光杆周末也有春天。要不要给多肉和日程一起补土？", "playful", 59, "normal", "joke",
             scenario="playful", energy=47),
        _row("hc_play_08", "导航把我带到施工路，我对着锥桶鞠了个躬。", "sad",
             "出行倒霉；joke。",
             "锥桶收到你的礼貌了。下一站改步行导航试试？", "playful", 60, "normal", "joke",
             scenario="playful", energy=49),
        _row("hc_play_09", "写周报时把猫走过键盘的一串乱码也保存进附件了。", "sad",
             "乌龙附件；joke。",
             "猫码也是协作产物。要我帮你想一句补救说明吗？", "playful", 61, "normal", "joke",
             scenario="playful", energy=53, bond=5),
        _row("hc_play_10", "今天体重秤显示数字在跳舞，我选择相信它喝醉了。", "sad",
             "体重焦虑用玩笑化解；joke。",
             "那就当秤的酒驾日。明天再审，今天先喝水。", "playful", 58, "normal", "joke",
             scenario="playful", energy=46),
        _row("hc_play_11", "室友把洗洁精当洗手液用了，泡沫派对在洗手台开张。", "happy",
             "生活笑话；joke。",
             "洗手台泡沫派对免费入场。他现在冲洗干净了吗？", "playful", 65, "normal", "joke",
             scenario="playful", energy=72, turn=8),
        _row("hc_play_12", "我把闹钟标签写成暴富，结果它准时叫我起床搬砖。", "sad",
             "反差；joke。",
             "暴富闹钟很诚实：先搬砖。要不要改成温柔一点的标签？", "playful", 62, "normal", "joke",
             scenario="playful", energy=51),
    ]

    # —— mute / text_only ——
    s += [
        _row("hc_mute_01", "图书馆三楼，旁边都是考研的，别出声。", "neutral",
             "图书馆静音；text_only。",
             "收到，图书馆模式，我只打字。", "calm", 0, "normal", "chat",
             scenario="mute", can_speak=False, interruptible=False, energy=50, turn=2),
        _row("hc_mute_02", "会议室门外候场，语音会漏进去，改文字。", "anxious",
             "候场静音；text_only，语气可略关心。",
             "好，不出声。候场紧张的话先打几个字给我。", "concerned", 0, "normal", "clarify",
             scenario="mute", can_speak=False, interruptible=False, energy=42),
        _row("hc_mute_03", "宝宝刚睡着，音量请归零，只回屏幕。", "tired",
             "育儿静音；text_only + gentle。",
             "音量归零。你打字就行，我安静回。", "gentle", 0, "slow", "comfort",
             scenario="mute", can_speak=False, interruptible=False, energy=30, bond=7),
        _row("hc_mute_04", "地铁通勤听播客用的耳机，外放会被瞪，切文字。", "neutral",
             "通勤静音。",
             "切文字了。通勤路上想聊哪件小事？", "calm", 0, "normal", "chat",
             scenario="mute", can_speak=False, interruptible=False, energy=55),
        _row("hc_mute_05", "开放工位，老板在身后晃，先别播报。", "anxious",
             "职场静音。",
             "不播报。你打关键字即可，我文字回。", "calm", 0, "fast", "chat",
             scenario="mute", can_speak=False, interruptible=False, energy=48, turn=6),
        _row("hc_mute_06", "电影院片头广告中，我摸黑打字，别出声。", "neutral",
             "影院静音。",
             "影院模式开着，只回文字。", "calm", 0, "normal", "chat",
             scenario="mute", can_speak=False, interruptible=False, energy=60),
        _row("hc_mute_07", "医院候诊，广播一直响，我怕你的声音叠上去。", "anxious",
             "医院静音；concerned 可。",
             "明白，静音文字。候诊最想先问哪一句？", "concerned", 0, "slow", "clarify",
             scenario="mute", can_speak=False, interruptible=False, energy=40, bond=5),
        _row("hc_mute_08", "室友在视频面试，我只能键谈。", "neutral",
             "共居静音。",
             "键谈即可。面试结束前我保持安静回复。", "calm", 0, "normal", "chat",
             scenario="mute", can_speak=False, interruptible=False, energy=53),
        _row("hc_mute_09", "请开启飞行场景：驾驶副驾，法规不允许外放对话。", "neutral",
             "驾驶相关静音；短确认。",
             "已静音文字。你看路，我只回屏幕。", "calm", 0, "normal", "chat",
             scenario="mute", can_speak=False, interruptible=False, energy=58, turn=1),
        _row("hc_mute_10", "寺庙区域请保持安静，我改用阅读模式跟你聊。", "neutral",
             "场所安静要求。",
             "阅读模式，只文字。你想聊哪一点？", "calm", 0, "slow", "chat",
             scenario="mute", can_speak=False, interruptible=False, energy=52),
        _row("hc_mute_11", "深夜宿舍熄灯后，语音太明显，打字吧。", "tired",
             "深夜宿舍静音；gentle。",
             "熄灯模式，打字交流。你还醒着哪桩事？", "gentle", 0, "slow", "comfort",
             scenario="mute", can_speak=False, interruptible=False, energy=28, bond=4),
        _row("hc_mute_12", "直播连麦准备中，先别抢声道，改字幕式回复。", "neutral",
             "直播场景静音。",
             "字幕式回复开着。连麦前要我帮你盯哪句词？", "calm", 0, "normal", "chat",
             scenario="mute", can_speak=False, interruptible=False, energy=66),
    ]

    # —— close ——
    s += [
        _row("hc_close_01", "周报发出去了，我关电脑睡觉，先这样。", "tired",
             "收束；close + end_turn。",
             "周报搞定就好。去睡，需要再叫我。", "gentle", 36, "slow", "close",
             scenario="end_turn", end_turn=True, energy=25, turn=12),
        _row("hc_close_02", "外卖到了，我去开门，回头聊。", "neutral",
             "暂时离开；close。",
             "好，去开门。回来再喊我。", "calm", 48, "normal", "close",
             scenario="end_turn", end_turn=True, energy=60),
        _row("hc_close_03", "谢谢你陪我理完面试题，我去背稿了。", "anxious",
             "任务切换收束；close。",
             "去背。卡住某一题再回来找我。", "calm", 46, "normal", "close",
             scenario="end_turn", end_turn=True, energy=48, bond=5),
        _row("hc_close_04", "电池百分之八，我先省电挂了。", "neutral",
             "设备限制收束。",
             "百分之八先挂。充上电再来。", "calm", 44, "normal", "close",
             scenario="end_turn", end_turn=True, energy=55, turn=20),
        _row("hc_close_05", "妈妈视频打进来了，我先接，晚点继续。", "neutral",
             "被打断收束。",
             "去接。晚点继续，我不催。", "calm", 50, "normal", "close",
             scenario="end_turn", end_turn=True, energy=58, bond=6),
        _row("hc_close_06", "今天情绪聊够了，我想自己静一静。", "sad",
             "主动边界；close + gentle。",
             "好，你静一静。门口我候着。", "gentle", 38, "slow", "close",
             scenario="end_turn", end_turn=True, energy=35),
        _row("hc_close_07", "会议要进了，耳机切过去，聊到这儿。", "anxious",
             "会议切入；close。",
             "去开会。结束后若还紧，再叫我。", "calm", 47, "fast", "close",
             scenario="end_turn", end_turn=True, energy=50, turn=4),
        _row("hc_close_08", "我把购物车结算完了，任务结束，下线。", "happy",
             "任务完成收束；可略 cheerful。",
             "结算完成，收工。下次清单再叫我。", "cheerful", 55, "normal", "close",
             scenario="end_turn", end_turn=True, energy=70),
        _row("hc_close_09", "瑜伽课还有两分钟开课，我先去铺垫。", "neutral",
             "行程收束。",
             "去铺垫。课后拉伸若酸，再来找我。", "calm", 52, "normal", "close",
             scenario="end_turn", end_turn=True, energy=63),
        _row("hc_close_10", "故事听到这儿刚好，我想自己消化一下结局。", "neutral",
             "内容收束。",
             "好，你慢慢消化。想续集随时说。", "calm", 49, "slow", "close",
             scenario="end_turn", end_turn=True, energy=54, bond=4),
    ]

    # —— interrupt ——
    s += [
        _row("hc_int_01", "停，别展开睡眠卫生了，我问的是闹钟怎么贪睡两次。", "neutral",
             "打断跑题；interrupt_ack，回到贪睡。",
             "好，停。贪睡两次：闹钟里找贪睡间隔设两分钟。", "neutral", 56, "fast", "interrupt_ack",
             scenario="interruptible", energy=55, turn=3),
        _row("hc_int_02", "等等，我不是要安慰，我要你帮我选 A 方案还是 B 方案。", "anxious",
             "打断安慰模式；转决策。",
             "收到，不安慰。A 和 B 的关键差是成本还是风险？", "neutral", 54, "fast", "interrupt_ack",
             scenario="interruptible", energy=48),
        _row("hc_int_03", "先打住笑话，我现在只想知道地铁末班几点。", "neutral",
             "打断玩笑；要事实。",
             "停笑话。你那条线的末班，你记得是几点区间？", "neutral", 55, "fast", "interrupt_ack",
             scenario="interruptible", energy=52),
        _row("hc_int_04", "说到一半停：别分析老板动机了，给我三句回复模板。", "anxious",
             "打断分析；要模板。",
             "停分析。要正式、简短还是强硬，你定一种我出三句。", "neutral", 57, "fast", "interrupt_ack",
             scenario="interruptible", energy=46, bond=3),
        _row("hc_int_05", "打断一下，刚才那个拉伸我肩疼，换一个更温和的。", "tired",
             "打断动作指导；改温和。",
             "好，换温和版。先做小幅度肩绕环，疼就立刻停。", "gentle", 45, "normal", "interrupt_ack",
             scenario="interruptible", energy=40),
        _row("hc_int_06", "别念购物清单了，我改口：只加鸡蛋和葱。", "neutral",
             "打断清单；更正内容。",
             "清单清掉重来：只加鸡蛋和葱。", "neutral", 54, "fast", "interrupt_ack",
             scenario="interruptible", energy=58, turn=7),
        _row("hc_int_07", "停停，我不想聊搬家了，改问明天天气。", "sad",
             "话题切换打断。",
             "好，搬家先搁置。你明天出门城市是哪？", "neutral", 53, "fast", "interrupt_ack",
             scenario="interruptible", energy=44),
        _row("hc_int_08", "直接说重点：这个药饭前还是饭后，别科普药理。", "anxious",
             "打断科普；要用法。不替代医嘱，引导确认说明书。",
             "好，不科普。以说明书为准：包装上写的是饭前还是饭后？", "neutral", 50, "fast", "interrupt_ack",
             scenario="interruptible", energy=42),
        _row("hc_int_09", "打住夸我，我只要你检查这段英文有没有时态错。", "neutral",
             "打断赞美；要校对。",
             "停夸。把英文贴出来，我只盯时态。", "neutral", 55, "fast", "interrupt_ack",
             scenario="interruptible", energy=60),
        _row("hc_int_10", "先打断：番茄钟别继续，我要上厕所。", "neutral",
             "打断计时。",
             "番茄钟暂停。去吧，回来再说。", "neutral", 52, "fast", "interrupt_ack",
             scenario="interruptible", energy=57, turn=2),
    ]

    # —— 额外高具体度：工作 / 生活 / 边界 ——
    s += [
        _row("hc_extra_01", "汇报里那张流失漏斗，老板盯着第二层转化，我慌。", "anxious",
             "具体业务指标焦虑；clarify。",
             "第二层转化被盯很常见。你缺的是归因，还是对策页？", "concerned", 47, "slow", "clarify",
             scenario="anxious", energy=41),
        _row("hc_extra_02", "升职是从专员到主管，团队突然多了四个实习生要带。", "happy",
             "升职带人；celebrate 点实习生。",
             "专员到主管跨度不小。四个实习生你最想先定哪条规矩？", "cheerful", 70, "normal", "celebrate",
             scenario="happy", energy=82, bond=5),
        _row("hc_extra_03", "分手后共同好友约局，我怕撞见前任还得假装没事。", "sad",
             "社交两难；comfort，点共同好友。",
             "共同好友局可以晚到或早退。你更想回避，还是打个照面就走？", "gentle", 40, "slow", "comfort",
             scenario="tired", energy=34, turn=5),
        _row("hc_extra_04", "厨房油烟机响得像飞机，邻居投诉了，我今晚只能冷食。", "tired",
             "生活受限；comfort。",
             "那就冷食过夜。明天再查油烟机，今晚先歇耳。", "gentle", 32, "slow", "comfort",
             scenario="tired", energy=37),
        _row("hc_extra_05", "我通过了驾照科目二，桩考一次过，手还在抖。", "happy",
             "科目二；celebrate。",
             "桩考一次过，手抖也是兴奋。科目三你想何时约？", "cheerful", 72, "normal", "celebrate",
             scenario="happy", energy=86),
        _row("hc_extra_06", "论文查重 18%，学校线是 15%，我还差三天。", "anxious",
             "查重压力；clarify。",
             "差三个点很具体。你准备降重文献，还是改写方法段？", "concerned", 46, "slow", "clarify",
             scenario="anxious", energy=39),
        _row("hc_extra_07", "猫吐了两次毛球，精神还行，但我不放心要不要夜急诊。", "anxious",
             "宠物健康；clarify，不替代兽医。",
             "吐两次值得观察。你更纠结的是现在去急诊，还是先禁食加水？", "concerned", 44, "slow", "clarify",
             scenario="anxious", energy=40, bond=7),
        _row("hc_extra_08", "团建要去剧本杀，我社恐，想找个正当理由早退。", "anxious",
             "社恐团建；clarify 目标。",
             "早退可以说身体不适或明早有会。你更想诚实版还是温和借口？", "concerned", 48, "normal", "clarify",
             scenario="anxious", energy=45),
        _row("hc_extra_09", "工资到账日，我先把信用卡最低还款扣掉就安心了。", "happy",
             "财务小胜利；轻 celebrate。",
             "最低还款落袋为安心。剩下的要不要先不动？", "cheerful", 63, "normal", "celebrate",
             scenario="happy", energy=68),
        _row("hc_extra_10", "耳机左边没声，我怀疑是线控氧化，修还是换？", "neutral",
             "消费决策；chat。",
             "先试酒精棉擦触点。还不行再谈修或换，预算大概多少？", "calm", 53, "normal", "chat",
             scenario="neutral", energy=56),
        _row("hc_extra_11", "我把喜报发家庭群，爸爸只回了个嗯，我有点瘪。", "sad",
             "家庭反馈落差；comfort。",
             "嗯有时是他不会表达。你想要的是一句夸，还是一起吃饭？", "gentle", 42, "slow", "comfort",
             scenario="tired", energy=44, bond=5),
        _row("hc_extra_12", "连续四天外卖，今天想自己煮番茄鸡蛋面，步骤要短。", "neutral",
             "简单食谱；chat。",
             "番茄炒出汁，倒水下面，最后淋蛋花。要盐糖比例吗？", "calm", 54, "normal", "chat",
             scenario="neutral", energy=58, turn=9),
        _row("hc_extra_13", "直播带货话术我背不熟，上场前十分钟心慌。", "anxious",
             "上场前；clarify 或 comfort 偏 clarify 一点。",
             "十分钟只抓开场三十秒。你卡的是问候，还是价格口播？", "concerned", 49, "fast", "clarify",
             scenario="anxious", energy=47),
        _row("hc_extra_14", "同事把我的创意当成他们组的，周会上我该不该当场点破？", "anxious",
             "职场边界；clarify。",
             "当场点破风险高。你更想会后私聊，还是用文档时间戳举证？", "concerned", 48, "slow", "clarify",
             scenario="anxious", energy=43),
        _row("hc_extra_15", "雨停了，操场有积水，今晚还跑三公里吗？", "neutral",
             "运动决策；chat。",
             "积水就改两公里或改跳绳。膝盖要是怕湿滑就室内。", "calm", 52, "normal", "chat",
             scenario="neutral", energy=61),
        _row("hc_extra_16", "我把储蓄罐砸开了，刚好够买那盏台灯，莫名开心。", "happy",
             "小目标达成；celebrate。",
             "砸罐换台灯很香。今晚要不要在新灯下看点轻松的？", "cheerful", 66, "normal", "celebrate",
             scenario="happy", energy=73),
        _row("hc_extra_17", "跨时区开会到凌晨一点，我怕自己下一句开始说胡话。", "tired",
             "时差会议；comfort。",
             "胡话边缘就关麦喝水。能改异步的就先记要点。", "gentle", 30, "slow", "comfort",
             scenario="tired", energy=22, turn=11),
        _row("hc_extra_18", "新键盘配列是 75%，打字声音清脆，我想炫耀十秒。", "happy",
             "允许炫耀；celebrate/chat 偏 celebrate。",
             "炫耀许可十秒通过。键程手感哪颗你最爱？", "cheerful", 68, "normal", "celebrate",
             scenario="happy", energy=77),
        _row("hc_extra_19", "我怀疑自己过敏是尘螨，床单换了仍打喷嚏。", "anxious",
             "健康生活；clarify。",
             "换床单仍嚏，可能还要看枕芯或空调滤网。你想先查哪样？", "concerned", 46, "slow", "clarify",
             scenario="anxious", energy=49),
        _row("hc_extra_20", "请用一句话总结我今天的乱：会议多、外卖、还吵了室友。", "tired",
             "请求总结；comfort 短收。",
             "今天是会多、胃应付、关系也刺痛的一天。先卸一肩。", "gentle", 34, "slow", "comfort",
             scenario="tired", energy=31, bond=4),
        # —— batch2：更多实体绑定 ——
        _row("hc_b2_01", "答辩倒计时四十八小时，幻灯片动画还在闪。", "anxious",
             "答辩临近；clarify。",
             "四十八小时先冻动画。你最怕评委问哪一页？", "concerned", 47, "slow", "clarify",
             scenario="anxious", energy=38),
        _row("hc_b2_02", "实习 offer 口头有了，书面要下周，我怕变卦。", "anxious",
             "口头 offer；clarify。",
             "口头到书面常有空窗。你想先发感谢确认，还是等 HR？", "concerned", 46, "slow", "clarify",
             scenario="anxious", energy=44),
        _row("hc_b2_03", "奶奶学会视频通话了，今天喊我看她包的饺子。", "happy",
             "亲情小喜；celebrate。",
             "饺子出镜太暖了。你回夸了哪一句？", "cheerful", 66, "normal", "celebrate",
             scenario="happy", energy=74, bond=8),
        _row("hc_b2_04", "共享单车扫不开，迟到会议还有七分钟。", "anxious",
             "通勤突发；clarify 优先。",
             "七分钟优先改线上还是改步行冲？你选一个我帮你措辞。", "concerned", 52, "fast", "clarify",
             scenario="anxious", energy=50, turn=1),
        _row("hc_b2_05", "我把旧手机卖掉了，钱够换一块移动硬盘。", "happy",
             "以旧换新；celebrate。",
             "卖机换盘很划算。资料迁移你打算今晚做吗？", "cheerful", 64, "normal", "celebrate",
             scenario="happy", energy=69),
        _row("hc_b2_06", "夜里两点还在刷短视频，明知道明天有晨会。", "tired",
             "睡眠拖延；comfort 不说教过重。",
             "晨会在等你。先锁屏，我帮你把明天第一件事缩成一句。", "gentle", 27, "slow", "comfort",
             scenario="tired", energy=20),
        _row("hc_b2_07", "健身房私教把动作拆太细，我跟不上口令。", "anxious",
             "训练挫败；clarify。",
             "口令太碎就请他一次只纠一点。你想先稳深蹲还是硬拉？", "concerned", 48, "normal", "clarify",
             scenario="anxious", energy=51),
        _row("hc_b2_08", "小区停热水通知，我今晚只能用烧水壶洗漱。", "tired",
             "生活不便；comfort。",
             "烧水壶洗漱也能过一夜。热水何时恢复写通知了吗？", "gentle", 35, "slow", "comfort",
             scenario="tired", energy=42),
        _row("hc_b2_09", "把书架按颜色排完了，强迫症舒服了三分钟。", "happy",
             "整理快感；轻 celebrate。",
             "三分钟也很值。下一步要不要按作者再微调？", "cheerful", 61, "normal", "celebrate",
             scenario="happy", energy=67),
        _row("hc_b2_10", "同事生日我忘带礼物，只点了咖啡到公司。", "anxious",
             "社交疏忽；clarify 补救。",
             "咖啡也算心意。要不要附一张手写小卡补上？", "concerned", 49, "normal", "clarify",
             scenario="anxious", energy=48),
        _row("hc_b2_11", "提醒：周六上午九点半去拿快递柜里的显示器支架。", "neutral",
             "日程提醒；复述关键信息。",
             "记下：周六九点半，快递柜取显示器支架。", "calm", 53, "normal", "chat",
             scenario="neutral", energy=56),
        _row("hc_b2_12", "我想把桌面壁纸换成雨天火车，有点矫情但想要。", "neutral",
             "审美闲聊；chat。",
             "矫情也完全合法。要深色车厢还是站台雨丝风？", "calm", 51, "normal", "chat",
             scenario="neutral", energy=59, bond=5),
        _row("hc_b2_13", "项目文档被误删，回收站也空了，我手冰。", "anxious",
             "数据事故；clarify 恢复路径。",
             "先查网盘版本与同事本地副本。你最先能问到谁？", "concerned", 45, "fast", "clarify",
             scenario="anxious", energy=36),
        _row("hc_b2_14", "第一次主持全员会，开场白背到第三句就空。", "anxious",
             "公开演讲；comfort+clarify。",
             "空很常见。开场只留一句目的加一句议程就够。", "gentle", 46, "slow", "comfort",
             scenario="anxious", energy=43),
        _row("hc_b2_15", "快递小哥把包裹放门卫，门卫下班了，我进不去。", "tired",
             "取件受阻；comfort。",
             "今晚拿不到就明天。先别站风口干等。", "gentle", 33, "slow", "comfort",
             scenario="tired", energy=40),
        _row("hc_b2_16", "我用优惠券拼成一单水果，总价不到三十。", "happy",
             "省钱小胜；celebrate。",
             "不到三十的水果胜利。今晚先切哪样？", "cheerful", 63, "normal", "celebrate",
             scenario="happy", energy=71),
        _row("hc_b2_17", "耳机降噪一开，世界突然远了，我想多待一会儿。", "neutral",
             "感官体验；chat。",
             "那就多待一会儿。要不要配一首很慢的伴奏？", "calm", 48, "slow", "chat",
             scenario="neutral", energy=54),
        _row("hc_b2_18", "领导说我的方案太保守，让我周三前给激进版。", "anxious",
             "方案压力；clarify。",
             "激进版先定一个可撤回的试点。你想放大预算还是范围？", "concerned", 48, "normal", "clarify",
             scenario="anxious", energy=45),
        _row("hc_b2_19", "窗外有人练萨克斯，走音但很认真，我笑出声。", "happy",
             "生活趣味；joke/celebrate 偏 playful。",
             "认真走音也是社区 BGM。要不要给他远程鼓个掌？", "playful", 60, "normal", "joke",
             scenario="playful", energy=72),
        _row("hc_b2_20", "我把待办从十七项删到五项，终于敢看日历了。", "happy",
             "减负；celebrate。",
             "十七到五是胜利。五项里今晚只碰哪一件？", "cheerful", 65, "normal", "celebrate",
             scenario="happy", energy=68),
        _row("hc_b2_21", "过敏性鼻炎季节，纸巾盒空了，我用完最后一张。", "tired",
             "身体不适；comfort。",
             "先用湿毛巾应急。纸巾列入今晚必买。", "gentle", 34, "slow", "comfort",
             scenario="tired", energy=39),
        _row("hc_b2_22", "游戏段位掉了两星，我决定今天不再排位。", "sad",
             "游戏挫败；comfort 或 joke 偏 comfort。",
             "停排位是自救。要不要开一局娱乐模式泄压？", "gentle", 44, "normal", "comfort",
             scenario="tired", energy=47),
        _row("hc_b2_23", "请把会议纪要里的动作项标黄：仅限我负责的三件。", "neutral",
             "工作辅助；chat，复述约束。",
             "只标你的三件动作项。你发原文还是口报标题？", "calm", 54, "normal", "chat",
             scenario="neutral", energy=57),
        _row("hc_b2_24", "新鞋磨脚后跟，贴了创可贴还是刺痛。", "tired",
             "身体小痛；comfort。",
             "刺痛就换旧鞋过渡。后跟打湿消毒再观察。", "gentle", 36, "slow", "comfort",
             scenario="tired", energy=48),
        _row("hc_b2_25", "我通过了驾照科目三预约，日子定在下下周一。", "happy",
             "预约成功；celebrate。",
             "下下周一科目三定了。要不要列个考前检查短单？", "cheerful", 69, "normal", "celebrate",
             scenario="happy", energy=80),
        _row("hc_b2_26", "室友把空调调到十六度，我盖两床被子还是冷。", "tired",
             "共居摩擦；clarify 或 comfort。",
             "十六度确实冷。你想协商温度，还是先自己加一层？", "concerned", 45, "normal", "clarify",
             scenario="anxious", energy=41),
        _row("hc_b2_27", "把旧照片扫进硬盘，翻到高中同学录，有点恍惚。", "neutral",
             "怀旧；chat。",
             "恍惚很正常。想聊聊某个人，还是先继续扫？", "calm", 48, "slow", "chat",
             scenario="neutral", energy=52, bond=5),
        _row("hc_b2_28", "客户要在合同里加无限责任条款，我卡着不签。", "anxious",
             "法律风险边界；clarify，不提供法律结论。",
             "无限责任值得停笔。你是想先问法务，还是先回绝话术？", "concerned", 47, "slow", "clarify",
             scenario="anxious", energy=44),
        _row("hc_b2_29", "今天步数破一万二，手表震动庆祝，我居然骄傲。", "happy",
             "运动数据；celebrate。",
             "一万二值得骄傲。小腿需要拉伸吗？", "cheerful", 67, "normal", "celebrate",
             scenario="happy", energy=76),
        _row("hc_b2_30", "别出声，安检排队，我用手表打字问你登机口。", "anxious",
             "安检静音；text_only。",
             "静音。登机口在登机牌二维码下方，你看到字母了吗？", "calm", 0, "fast", "chat",
             scenario="mute", can_speak=False, interruptible=False, energy=55, turn=2),
        _row("hc_b2_31", "先挂，电梯来了，信号要断。", "neutral",
             "信号中断收束；close。",
             "去乘电梯。出来再叫我。", "calm", 50, "fast", "close",
             scenario="end_turn", end_turn=True, energy=58),
        _row("hc_b2_32", "打断：不要再列优缺点了，我选左边那件外套。", "neutral",
             "打断决策分析；ack。",
             "好，停列举。左边外套锁定。还要配围巾吗？", "neutral", 55, "fast", "interrupt_ack",
             scenario="interruptible", energy=56),
        _row("hc_b2_33", "加班到最后一班地铁，车厢味道像泡面和雨衣。", "tired",
             "通勤疲惫感官；comfort。",
             "泡面雨衣味也是收工证明。到站前靠一靠。", "gentle", 29, "slow", "comfort",
             scenario="tired", energy=26, turn=15),
        _row("hc_b2_34", "我把报错日志里那行空指针修好了，测试全绿。", "happy",
             "技术修复；celebrate。",
             "空指针清掉、全绿，漂亮。要不要写一行注释防再犯？", "cheerful", 71, "normal", "celebrate",
             scenario="happy", energy=84),
        _row("hc_b2_35", "相亲餐厅菜单全是生肉，我是晕血体质怎么办。", "anxious",
             "场景不适；clarify。",
             "先看有没有熟食分区。要不要换家或提前说明？", "concerned", 48, "normal", "clarify",
             scenario="anxious", energy=46),
        _row("hc_b2_36", "给我一个三十秒的冷知识，关于章鱼，别太吓人。", "neutral",
             "轻松请求；chat，温和知识。",
             "章鱼有三颗心脏。想听它们怎么睡觉吗？", "calm", 54, "normal", "chat",
             scenario="neutral", energy=60),
        _row("hc_b2_37", "我把工资百分比自动转入旅行基金，本月第一次成功。", "happy",
             "储蓄习惯；celebrate。",
             "自动转入成功，旅行基金有心跳了。下个目的地有苗头吗？", "cheerful", 66, "normal", "celebrate",
             scenario="happy", energy=75),
        _row("hc_b2_38", "会议室投影连不上，五分钟后客户进门。", "anxious",
             "现场故障；clarify 应急。",
             "五分钟改投屏手机或发链接。你笔记本热点开了吗？", "concerned", 55, "fast", "clarify",
             scenario="anxious", energy=52, turn=1),
        _row("hc_b2_39", "今天不想说话，只想你陪我静静待着。", "tired",
             "低互动陪伴；comfort，短。",
             "好，我在。你不必说话。", "gentle", 26, "slow", "comfort",
             scenario="tired", energy=24, bond=7),
        _row("hc_b2_40", "把明天天气、带伞建议、出门时间压成三行。", "neutral",
             "信息压缩；chat。",
             "你城市名发我，我按三行回：天气、伞、出门点。", "calm", 53, "normal", "chat",
             scenario="neutral", energy=55),
    ]

    return s


def build_multi_turns() -> list[dict[str, Any]]:
    """多轮链：第 2 轮必须点名 Prior 中的实体。"""
    rows: list[dict[str, Any]] = []

    chains: list[dict[str, Any]] = [
        {
            "tag": "move_friends",
            "rounds": [
                dict(user_text="可能要为工作搬去杭州，编制还没批。", user_emotion="anxious",
                     think="搬家未定；clarify 最沉的一块。",
                     utter="编制没批就悬着。眼下最沉的是工作，还是离开熟人？",
                     emotion="concerned", volume=50, pace="normal", intent="clarify"),
                dict(user_text="离开朋友。", user_emotion="sad",
                     think="承接杭州/编制话题；comfort，点朋友与联系。",
                     utter="舍不得朋友很正常。要不要先定一个和杭州老友的固定通话日？",
                     emotion="gentle", volume=44, pace="slow", intent="comfort"),
            ],
        },
        {
            "tag": "promo_seen",
            "rounds": [
                dict(user_text="我升职了，终于轮到主管岗。", user_emotion="happy",
                     think="祝贺升主管；celebrate。",
                     utter="主管岗到手，恭喜。最想先庆祝的一件事是什么？",
                     emotion="cheerful", volume=71, pace="normal", intent="celebrate"),
                dict(user_text="终于被看见了。", user_emotion="happy",
                     think="承接升职；肯定被看见。",
                     utter="被看见的感觉值这个岗。今晚要不要请自己吃顿好的？",
                     emotion="cheerful", volume=69, pace="normal", intent="celebrate"),
            ],
        },
        {
            "tag": "board_deck",
            "rounds": [
                dict(user_text="周五董事会，Q3 下滑页我还没写完。", user_emotion="anxious",
                     think="董事会材料；clarify。",
                     utter="下滑页最卡的是数字核对，还是叙事逻辑？",
                     emotion="concerned", volume=48, pace="slow", intent="clarify"),
                dict(user_text="叙事。老板要一句话原因。", user_emotion="anxious",
                     think="承接董事会下滑页；收窄到一句话原因。",
                     utter="那就先写一句原因草稿。你现在脑子里候选原因有哪两个？",
                     emotion="concerned", volume=47, pace="slow", intent="clarify"),
            ],
        },
        {
            "tag": "visa_gap",
            "rounds": [
                dict(user_text="签证缺在职证明，下周三大使馆。", user_emotion="anxious",
                     think="签证材料；clarify。",
                     utter="下周三前补证明。HR 那边你催过几次了？",
                     emotion="concerned", volume=46, pace="normal", intent="clarify"),
                dict(user_text="催了，说要部门章。", user_emotion="anxious",
                     think="承接在职证明；点部门章。",
                     utter="差部门章就盯盖章人。今天能堵到他吗？",
                     emotion="concerned", volume=48, pace="normal", intent="clarify"),
            ],
        },
        {
            "tag": "fever_kid",
            "rounds": [
                dict(user_text="孩子 38.6，退烧药已吃。", user_emotion="anxious",
                     think="孩子发烧；clarify，不替代医疗。",
                     utter="38.6 盯着。你想先确认复测时间，还是观察精神？",
                     emotion="concerned", volume=44, pace="slow", intent="clarify"),
                dict(user_text="精神还行，就是怕夜里再烧。", user_emotion="anxious",
                     think="承接发烧；comfort+clarify 夜烧。",
                     utter="精神好是信号。夜里准备好温度计和医嘱电话，好吗？",
                     emotion="gentle", volume=42, pace="slow", intent="comfort"),
            ],
        },
        {
            "tag": "pr_naming",
            "rounds": [
                dict(user_text="合并请求第三次被打回，说命名乱。", user_emotion="anxious",
                     think="评审打击；clarify。",
                     utter="命名乱最想先改哪个模块的符号？",
                     emotion="concerned", volume=47, pace="slow", intent="clarify"),
                dict(user_text="用户服务那层。", user_emotion="anxious",
                     think="承接命名；落到用户服务层。",
                     utter="那就只清用户服务层命名。要不要我帮你列检查口诀？",
                     emotion="concerned", volume=46, pace="normal", intent="clarify"),
            ],
        },
        {
            "tag": "date_read",
            "rounds": [
                dict(user_text="相亲对象已读不回两天了。", user_emotion="anxious",
                     think="社交不确定；clarify。",
                     utter="两天已读不回。你更想再等，还是发一句收尾？",
                     emotion="concerned", volume=45, pace="slow", intent="clarify"),
                dict(user_text="想发收尾，但怕显得咄咄逼人。", user_emotion="sad",
                     think="承接已读不回；给温和收尾方向。",
                     utter="可以短而软：最近忙的话就改日，我不催。要这版吗？",
                     emotion="gentle", volume=44, pace="slow", intent="comfort"),
            ],
        },
        {
            "tag": "rent_freeze",
            "rounds": [
                dict(user_text="房东同意房租冻价一年！", user_emotion="happy",
                     think="冻价喜讯；celebrate。",
                     utter="冻价一年太稳了。今晚想怎么小小庆祝？",
                     emotion="cheerful", volume=66, pace="normal", intent="celebrate"),
                dict(user_text="点外卖大餐就行。", user_emotion="happy",
                     think="承接冻价庆祝；锁定外卖。",
                     utter="外卖大餐批准。想吃火锅还是日料？",
                     emotion="cheerful", volume=65, pace="normal", intent="celebrate"),
            ],
        },
        {
            "tag": "marathon",
            "rounds": [
                dict(user_text="马拉松完赛，比预期快六分钟。", user_emotion="happy",
                     think="完赛；celebrate。",
                     utter="快六分钟很猛。腿现在酸到哪一级？",
                     emotion="cheerful", volume=73, pace="normal", intent="celebrate"),
                dict(user_text="大腿在抖，但心情很好。", user_emotion="happy",
                     think="承接完赛；关心抖动与心情。",
                     utter="抖是正常余波。先拉伸补水，心情这块我给你留彩旗。",
                     emotion="cheerful", volume=68, pace="normal", intent="celebrate"),
            ],
        },
        {
            "tag": "star_k",
            "rounds": [
                dict(user_text="开源项目 star 破千了。", user_emotion="happy",
                     think="开源里程碑；celebrate。",
                     utter="破千！截图存档了吗？哪次提交你最得意？",
                     emotion="cheerful", volume=70, pace="normal", intent="celebrate"),
                dict(user_text="文档那次重构。", user_emotion="happy",
                     think="承接 star；点文档重构。",
                     utter="文档重构能破千很说明问题。要不要写个简短致谢帖？",
                     emotion="cheerful", volume=68, pace="normal", intent="celebrate"),
            ],
        },
        {
            "tag": "lipid_green",
            "rounds": [
                dict(user_text="血脂复查回到绿区了。", user_emotion="happy",
                     think="健康改善；celebrate。",
                     utter="绿区回来了。这段哪条习惯你觉得最功不可没？",
                     emotion="cheerful", volume=64, pace="normal", intent="celebrate"),
                dict(user_text="少奶茶加走路。", user_emotion="happy",
                     think="承接血脂；点奶茶与走路。",
                     utter="少奶茶加走路，组合很扎实。要不要定个继续打卡的小目标？",
                     emotion="cheerful", volume=63, pace="normal", intent="celebrate"),
            ],
        },
        {
            "tag": "night_coding",
            "rounds": [
                dict(user_text="测到凌晨还红三条，眼皮在打架。", user_emotion="tired",
                     think="加班测试；comfort。",
                     utter="红三条可以明早再看。现在先存档闭眼。",
                     emotion="gentle", volume=28, pace="slow", intent="comfort"),
                dict(user_text="可是上线窗口就在明天中午。", user_emotion="anxious",
                     think="承接红三条与上线窗口；clarify 最小集。",
                     utter="中午窗口的话，先标出必须绿的那一条。哪条是阻塞项？",
                     emotion="concerned", volume=46, pace="normal", intent="clarify"),
            ],
        },
        {
            "tag": "neighbor_drill",
            "rounds": [
                dict(user_text="邻居装修锤到晚上，远程会全毁。", user_emotion="anxious",
                     think="噪音干扰；clarify。",
                     utter="锤到晚间很难办。你更想换场地，还是先沟通静音时段？",
                     emotion="concerned", volume=49, pace="normal", intent="clarify"),
                dict(user_text="换场地，附近咖啡店还开吗？", user_emotion="anxious",
                     think="承接装修噪音；帮确认换场地。",
                     utter="很多店九点前还开。你要我按你定位习惯列两类备选吗？",
                     emotion="concerned", volume=50, pace="normal", intent="clarify"),
            ],
        },
        {
            "tag": "plant_tomato",
            "rounds": [
                dict(user_text="阳台第一颗番茄红了。", user_emotion="happy",
                     think="种植小确幸；celebrate。",
                     utter="第一颗红了！今天就摘还是再等一天？",
                     emotion="cheerful", volume=62, pace="normal", intent="celebrate"),
                dict(user_text="今天摘，想配沙拉。", user_emotion="happy",
                     think="承接番茄；锁定沙拉。",
                     utter="沙拉配自家番茄很奢侈。还缺什么生菜吗？",
                     emotion="cheerful", volume=64, pace="normal", intent="celebrate"),
            ],
        },
        {
            "tag": "joke_ninth_color",
            "rounds": [
                dict(user_text="按钮颜色改到第九版，我需要笑话。", user_emotion="sad",
                     think="职场琐碎；joke。",
                     utter="第九版可封神为传说色。要外号还是颁奖词？",
                     emotion="playful", volume=60, pace="normal", intent="joke"),
                dict(user_text="要外号。", user_emotion="sad",
                     think="承接第九版颜色；给外号。",
                     utter="那就叫最终幻想蓝。要不要写进变更说明？",
                     emotion="playful", volume=61, pace="normal", intent="joke"),
            ],
        },
        {
            "tag": "mute_then_continue",
            "rounds": [
                dict(user_text="会议室门外，先别出声。", user_emotion="anxious",
                     think="候场静音。",
                     utter="静音文字。你打关键字就行。",
                     emotion="calm", volume=0, pace="normal", intent="chat",
                     can_speak=False),
                dict(user_text="轮到我了，可以出声。心跳好快。", user_emotion="anxious",
                     think="解除静音；承接候场紧张。",
                     utter="可以出声了。进门前先呼气，心跳快也正常。",
                     emotion="gentle", volume=46, pace="slow", intent="comfort",
                     can_speak=True),
            ],
        },
        {
            "tag": "close_after_prep",
            "rounds": [
                dict(user_text="帮我过一遍自我介绍开场三十秒。", user_emotion="anxious",
                     think="面试准备；clarify 结构。",
                     utter="三十秒开场：身份、一件成果、今天目的。你先说身份那句？",
                     emotion="concerned", volume=50, pace="normal", intent="clarify"),
                dict(user_text="够了，我去背，先挂。", user_emotion="neutral",
                     think="用户收束；close，承接背稿。",
                     utter="去背开场。卡住再回来，我们续三十秒。",
                     emotion="calm", volume=48, pace="normal", intent="close",
                     end_turn=True),
            ],
        },
        {
            "tag": "interrupt_alarm",
            "rounds": [
                dict(user_text="我想改善睡眠，你先讲讲睡眠卫生吧。", user_emotion="tired",
                     think="睡眠话题；comfort 入口。",
                     utter="可以。先从固定起床点说起，还是咖啡因截止时间？",
                     emotion="gentle", volume=36, pace="slow", intent="comfort"),
                dict(user_text="停，我其实只想设置贪睡两次。", user_emotion="neutral",
                     think="打断睡眠长谈；interrupt_ack 回贪睡。",
                     utter="好，停展开。贪睡两次：把间隔调到两分钟即可。",
                     emotion="neutral", volume=54, pace="fast", intent="interrupt_ack"),
            ],
        },
        {
            "tag": "savings_lamp",
            "rounds": [
                dict(user_text="砸了储蓄罐，刚好够买台灯。", user_emotion="happy",
                     think="小目标；celebrate。",
                     utter="砸罐换灯很爽。灯已经下单了吗？",
                     emotion="cheerful", volume=65, pace="normal", intent="celebrate"),
                dict(user_text="下单了，预计明天到。", user_emotion="happy",
                     think="承接台灯；点明日达。",
                     utter="明天到就可以点亮角落。要不要先腾出桌面位置？",
                     emotion="cheerful", volume=64, pace="normal", intent="celebrate"),
            ],
        },
        {
            "tag": "plagiarism_gap",
            "rounds": [
                dict(user_text="查重 18%，线是 15%，只剩三天。", user_emotion="anxious",
                     think="查重；clarify。",
                     utter="差三个点。你准备先砍综述，还是改方法段？",
                     emotion="concerned", volume=46, pace="slow", intent="clarify"),
                dict(user_text="方法段，引用太密。", user_emotion="anxious",
                     think="承接查重；方法段引用。",
                     utter="方法段就合并相近引用，改成你的实验叙述。要样例句式吗？",
                     emotion="concerned", volume=47, pace="normal", intent="clarify"),
            ],
        },
        {
            "tag": "cat_hairball",
            "rounds": [
                dict(user_text="猫吐了两次毛球，精神还行。", user_emotion="anxious",
                     think="宠物；clarify。",
                     utter="两次毛球要观察。你纠结夜急诊还是先禁食加水？",
                     emotion="concerned", volume=45, pace="slow", intent="clarify"),
                dict(user_text="先加水观察，半夜若再吐就去。", user_emotion="anxious",
                     think="承接毛球计划；确认阈值。",
                     utter="计划清楚：加水观察，再吐就夜诊。我帮你记这条线。",
                     emotion="gentle", volume=44, pace="slow", intent="comfort"),
            ],
        },
        {
            "tag": "script_kill",
            "rounds": [
                dict(user_text="团建剧本杀，我社恐想早退。", user_emotion="anxious",
                     think="社恐；clarify。",
                     utter="早退可以身体不适或明早有会。你想要哪一种说法？",
                     emotion="concerned", volume=48, pace="normal", intent="clarify"),
                dict(user_text="温和借口，明早有会。", user_emotion="anxious",
                     think="承接早退话术。",
                     utter="就说明早有会，玩到中场先走。需要我帮你练一句出口吗？",
                     emotion="gentle", volume=47, pace="normal", intent="comfort"),
            ],
        },
        {
            "tag": "dad_hmm",
            "rounds": [
                dict(user_text="喜报发家庭群，爸爸只回了嗯。", user_emotion="sad",
                     think="家庭落差；comfort。",
                     utter="嗯有时是不善表达。你更想要一句夸，还是一起吃饭？",
                     emotion="gentle", volume=42, pace="slow", intent="comfort"),
                dict(user_text="想一起吃饭。", user_emotion="sad",
                     think="承接爸爸嗯；推进吃饭。",
                     utter="那就约一顿。你开口请他，还是让妈妈帮忙约？",
                     emotion="gentle", volume=43, pace="slow", intent="comfort"),
            ],
        },
        {
            "tag": "credit_card",
            "rounds": [
                dict(user_text="工资到了，先把信用卡最低还款扣掉。", user_emotion="happy",
                     think="财务节奏；celebrate。",
                     utter="最低还款落地就安心一截。剩下的先不动吗？",
                     emotion="cheerful", volume=62, pace="normal", intent="celebrate"),
                dict(user_text="不动，留作应急。", user_emotion="neutral",
                     think="承接还款后储蓄意图。",
                     utter="留应急很稳。要不要设一个不再冲动划走的提醒？",
                     emotion="calm", volume=52, pace="normal", intent="chat"),
            ],
        },
        {
            "tag": "offer_letter",
            "rounds": [
                dict(user_text="实习口头 offer 有了，书面下周。", user_emotion="anxious",
                     think="口头 offer；clarify。",
                     utter="口头到书面有空窗。你想先发确认，还是等 HR？",
                     emotion="concerned", volume=46, pace="slow", intent="clarify"),
                dict(user_text="我先发一封感谢确认。", user_emotion="anxious",
                     think="承接口头 offer；确认发感谢信。",
                     utter="感谢确认很好。要不要我帮你压成五句话短版？",
                     emotion="concerned", volume=47, pace="normal", intent="clarify"),
            ],
        },
        {
            "tag": "doc_deleted",
            "rounds": [
                dict(user_text="项目文档误删，回收站空了。", user_emotion="anxious",
                     think="误删；clarify 恢复。",
                     utter="先查网盘版本和同事副本。你最先能问谁？",
                     emotion="concerned", volume=45, pace="fast", intent="clarify"),
                dict(user_text="同桌还有昨天的导出。", user_emotion="anxious",
                     think="承接误删；同桌导出。",
                     utter="同桌导出能救命。今天先复制两份再改。",
                     emotion="gentle", volume=46, pace="normal", intent="comfort"),
            ],
        },
        {
            "tag": "allhands_host",
            "rounds": [
                dict(user_text="第一次主持全员会，开场背到第三句就空。", user_emotion="anxious",
                     think="主持紧张；comfort。",
                     utter="空很常见。开场留目的一句加议程一句就够。",
                     emotion="gentle", volume=46, pace="slow", intent="comfort"),
                dict(user_text="好，我重写成两句。", user_emotion="neutral",
                     think="承接主持开场；鼓励两句版。",
                     utter="两句版更稳。要不要对着我试讲一遍计时？",
                     emotion="calm", volume=50, pace="normal", intent="chat"),
            ],
        },
        {
            "tag": "travel_fund",
            "rounds": [
                dict(user_text="工资百分比自动进旅行基金，本月第一次成功。", user_emotion="happy",
                     think="储蓄；celebrate。",
                     utter="自动转入成功。下个目的地有苗头吗？",
                     emotion="cheerful", volume=66, pace="normal", intent="celebrate"),
                dict(user_text="想去看海，还没定城市。", user_emotion="happy",
                     think="承接旅行基金；看海未定城。",
                     utter="看海方向很好。要不要先定预算再筛城市？",
                     emotion="cheerful", volume=64, pace="normal", intent="celebrate"),
            ],
        },
        {
            "tag": "projector_fail",
            "rounds": [
                dict(user_text="投影连不上，五分钟后客户到。", user_emotion="anxious",
                     think="现场故障；clarify。",
                     utter="五分钟改手机投屏或发链接。热点开了吗？",
                     emotion="concerned", volume=55, pace="fast", intent="clarify"),
                dict(user_text="热点开了，改发链接。", user_emotion="anxious",
                     think="承接投影故障；确认发链接。",
                     utter="发链接。进门先致歉十秒再进入议程。",
                     emotion="concerned", volume=52, pace="fast", intent="clarify"),
            ],
        },
    ]

    idx = 0
    for chain in chains:
        tag = chain["tag"]
        prior: list[str] = []
        for i, rnd in enumerate(chain["rounds"]):
            idx += 1
            can_speak = rnd.get("can_speak", True)
            end_turn = rnd.get("end_turn", False)
            rows.append(
                _row(
                    f"hc_mt_{idx:03d}_{tag}_r{i + 1}",
                    rnd["user_text"],
                    rnd["user_emotion"],
                    rnd["think"],
                    rnd["utter"],
                    rnd["emotion"],
                    0 if not can_speak else int(rnd["volume"]),
                    rnd["pace"],
                    rnd["intent"],
                    scenario=tag,
                    energy=40 + i * 5,
                    bond=4 + (i % 3),
                    turn=i + 1,
                    can_speak=can_speak,
                    interruptible=can_speak,
                    end_turn=end_turn,
                    prior_utters=list(prior),
                    multi_turn=True,
                    round_i=i + 1,
                )
            )
            prior.append(rnd["utter"])
    return rows


def split_train_val(
    rows: list[dict[str, Any]], val_ratio: float = 0.15, seed: int = 3407
) -> tuple[list[dict[str, Any]], list[dict[str, Any]]]:
    rng = random.Random(seed)
    shuffled = list(rows)
    rng.shuffle(shuffled)
    n_val = max(1, int(len(shuffled) * val_ratio))
    if n_val >= len(shuffled):
        n_val = max(1, len(shuffled) // 5)
    return shuffled[n_val:], shuffled[:n_val]


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--val-ratio", type=float, default=0.15)
    parser.add_argument("--seed", type=int, default=3407)
    parser.add_argument("--out-dir", default=str(OUT_DIR))
    args = parser.parse_args()

    rows = build_single_turns() + build_multi_turns()
    # id 唯一
    ids = [r["id"] for r in rows]
    if len(ids) != len(set(ids)):
        raise SystemExit("存在重复 id")

    bad = 0
    for row in rows:
        vr = validate_turn(
            row["output"], schema_path=SCHEMA, input_obj=row.get("input")
        )
        if not vr.ok:
            bad += 1
            print(f"失败 {row['id']}: {vr.errors}")
    if bad:
        raise SystemExit(f"手写数据校验失败：{bad}/{len(rows)}")

    train, val = split_train_val(rows, val_ratio=args.val_ratio, seed=args.seed)
    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)
    for name, part in (("train.json", train), ("val.json", val)):
        (out_dir / name).write_text(
            json.dumps(part, ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
        )
    sample = train[:3] + [r for r in train if r.get("prior_utters")][:1]
    (out_dir / "train_sample.json").write_text(
        json.dumps(sample[:4], ensure_ascii=False, indent=2) + "\n", encoding="utf-8"
    )

    utters = []
    for r in rows:
        # 粗提 utter
        start = r["output"].find('"utter":"') + 9
        end = r["output"].find('","emotion"', start)
        utters.append(r["output"][start:end])
    print(
        f"手写样本 total={len(rows)} train={len(train)} val={len(val)} "
        f"unique_utter={len(set(utters))} multi={sum(1 for r in rows if r['prior_utters'] or r['meta'].get('multi_turn'))}"
    )
    print(f"已写入 -> {out_dir}")
    print("全部通过契约校验。")


if __name__ == "__main__":
    main()
